name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test
    env:
      ATOTI_HIDE_EULA_MESSAGE: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.1.10"
      - run: poetry install
      - run: poetry run black --check app/ tests/
      - run: poetry run isort --check app/ tests/
      - run: poetry run pylint app/ tests/
      - run: poetry run mypy --package app --package tests
      - run: poetry run pytest
